import { describe, it, expect } from 'vitest'
import path from 'node:path'
import fs from 'node:fs/promises'
import os from 'node:os'

// sync.ts exports: runSync, consoleLogger, SyncLogger (interface), BackendConfig (interface), SyncOptions (interface)
// The internal functions (generateOperation, generateTagFiles, schemaToTs, etc.) are NOT exported.

describe('runSync integration', () => {
  it('generates output files from a local schema fixture', async () => {
    const { runSync } = await import('../../src/cli/sync')

    const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'pocketshot-sync-test-'))

    const fixtureSchema = path.resolve(__dirname, 'fixtures/sample-schema.json')

    try {
      await runSync({
        filePath: fixtureSchema,
        cwd: tmpDir,
        logger: {
          info: () => {},
          success: () => {},
          warn: () => {},
          error: () => {},
        },
      })

      const apiDir = path.join(tmpDir, 'src/api')
      const hooksDir = path.join(tmpDir, 'src/hooks/api')

      const apiFiles = await fs.readdir(apiDir)
      const hooksFiles = await fs.readdir(hooksDir)

      expect(apiFiles.length).toBeGreaterThan(0)
      expect(hooksFiles.length).toBeGreaterThan(0)

      // Expect a generated file for the 'index' tag (no tags in fixture → falls back to 'index')
      expect(apiFiles).toContain('index.ts')
      expect(hooksFiles).toContain('index.ts')
    } finally {
      await fs.rm(tmpDir, { recursive: true, force: true })
    }
  })

  it('uses pocketshot-specific banner comment', async () => {
    const { runSync } = await import('../../src/cli/sync')

    const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'pocketshot-sync-banner-'))
    const fixtureSchema = path.resolve(__dirname, 'fixtures/sample-schema.json')

    try {
      await runSync({
        filePath: fixtureSchema,
        cwd: tmpDir,
        logger: { info: () => {}, success: () => {}, warn: () => {}, error: () => {} },
      })

      const apiContent = await fs.readFile(path.join(tmpDir, 'src/api/index.ts'), 'utf8')
      expect(apiContent).toContain('// Generated by npx pocketshot sync')
      expect(apiContent).not.toContain('bunx snapshot sync')
    } finally {
      await fs.rm(tmpDir, { recursive: true, force: true })
    }
  })

  it('imports ApiError from @lastshotlabs/pocketshot (not snapshot)', async () => {
    const { runSync } = await import('../../src/cli/sync')

    const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'pocketshot-sync-apierror-'))
    const fixtureSchema = path.resolve(__dirname, 'fixtures/sample-schema.json')

    try {
      await runSync({
        filePath: fixtureSchema,
        cwd: tmpDir,
        logger: { info: () => {}, success: () => {}, warn: () => {}, error: () => {} },
      })

      const hooksContent = await fs.readFile(path.join(tmpDir, 'src/hooks/api/index.ts'), 'utf8')
      expect(hooksContent).toContain("from '@lastshotlabs/pocketshot'")
      expect(hooksContent).not.toContain("from '@lastshotlabs/snapshot'")
    } finally {
      await fs.rm(tmpDir, { recursive: true, force: true })
    }
  })

  it('imports api from default pocketshotImport path', async () => {
    const { runSync } = await import('../../src/cli/sync')

    const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'pocketshot-sync-import-'))
    const fixtureSchema = path.resolve(__dirname, 'fixtures/sample-schema.json')

    try {
      await runSync({
        filePath: fixtureSchema,
        cwd: tmpDir,
        logger: { info: () => {}, success: () => {}, warn: () => {}, error: () => {} },
      })

      const apiContent = await fs.readFile(path.join(tmpDir, 'src/api/index.ts'), 'utf8')
      expect(apiContent).toContain("from '@/lib/pocketshot'")
    } finally {
      await fs.rm(tmpDir, { recursive: true, force: true })
    }
  })

  it('respects custom pocketshotImport option', async () => {
    const { runSync } = await import('../../src/cli/sync')

    const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'pocketshot-sync-custom-'))
    const fixtureSchema = path.resolve(__dirname, 'fixtures/sample-schema.json')

    try {
      await runSync({
        filePath: fixtureSchema,
        cwd: tmpDir,
        pocketshotImport: '@/custom/pocketshot',
        logger: { info: () => {}, success: () => {}, warn: () => {}, error: () => {} },
      })

      const apiContent = await fs.readFile(path.join(tmpDir, 'src/api/index.ts'), 'utf8')
      expect(apiContent).toContain("from '@/custom/pocketshot'")
    } finally {
      await fs.rm(tmpDir, { recursive: true, force: true })
    }
  })

  it('reads pocketshotImport from pocketshot.config.json', async () => {
    const { runSync } = await import('../../src/cli/sync')

    const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'pocketshot-sync-config-'))
    const fixtureSchema = path.resolve(__dirname, 'fixtures/sample-schema.json')

    try {
      await fs.writeFile(
        path.join(tmpDir, 'pocketshot.config.json'),
        JSON.stringify({ pocketshotImport: '@/lib/ps' }),
        'utf8',
      )

      await runSync({
        filePath: fixtureSchema,
        cwd: tmpDir,
        logger: { info: () => {}, success: () => {}, warn: () => {}, error: () => {} },
      })

      const apiContent = await fs.readFile(path.join(tmpDir, 'src/api/index.ts'), 'utf8')
      expect(apiContent).toContain("from '@/lib/ps'")
    } finally {
      await fs.rm(tmpDir, { recursive: true, force: true })
    }
  })

  it('reads EXPO_PUBLIC_API_URL from .env', async () => {
    // This test just validates that the env var name used is EXPO_PUBLIC_API_URL
    const { runSync } = await import('../../src/cli/sync')

    const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'pocketshot-sync-env-'))
    const fixtureSchema = path.resolve(__dirname, 'fixtures/sample-schema.json')

    try {
      // We test this indirectly — if EXPO_PUBLIC_API_URL is set in .env
      // and no filePath/apiUrl is given, it should be used. But since we pass filePath,
      // the env path is not exercised here. We just verify the file still generates correctly.
      await fs.writeFile(
        path.join(tmpDir, '.env'),
        'EXPO_PUBLIC_API_URL=http://localhost:3000\n',
        'utf8',
      )
      await runSync({
        filePath: fixtureSchema,
        cwd: tmpDir,
        logger: { info: () => {}, success: () => {}, warn: () => {}, error: () => {} },
      })
      const apiFiles = await fs.readdir(path.join(tmpDir, 'src/api'))
      expect(apiFiles.length).toBeGreaterThan(0)
    } finally {
      await fs.rm(tmpDir, { recursive: true, force: true })
    }
  })
})
