import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { runEasWorkflow, runUpgradeWorkflow, runVerifyWorkflow } from '../../src/cli/workflows'

function cleanRoom() {
  const cwd = mkdtempSync(join(tmpdir(), 'pocketshot-workflows-'))
  mkdirSync(cwd, { recursive: true })
  writeFileSync(
    join(cwd, 'package.json'),
    JSON.stringify({
      name: 'clean-room',
      dependencies: {
        '@lastshotlabs/pocketshot': '^0.1.2',
        '@tanstack/react-query': '^5',
        expo: '~56.0.0',
        'expo-router': '~56.0.0',
        'expo-secure-store': '~56.0.0',
        jotai: '^2',
        react: '19.1.0',
        'react-native': '0.83.0',
        'react-native-safe-area-context': '~5.6.0',
        'react-native-screens': '~4.20.0',
      },
    }),
  )
  writeFileSync(
    join(cwd, 'app.json'),
    JSON.stringify({
      expo: {
        scheme: 'cleanroom',
        ios: { bundleIdentifier: 'com.lastshotlabs.cleanroom' },
        android: { package: 'com.lastshotlabs.cleanroom' },
        plugins: ['expo-router', 'expo-secure-store'],
      },
    }),
  )
  return cwd
}

describe('CLI release workflows', () => {
  it('plans and applies an upgrade idempotently with breaking diagnostics', () => {
    const cwd = cleanRoom()
    const plan = runUpgradeWorkflow({ cwd })
    expect(plan.changed).toBe(false)
    expect(plan.changes.some((item) => item.breaking)).toBe(true)

    expect(runUpgradeWorkflow({ cwd, write: true }).changed).toBe(true)
    expect(runUpgradeWorkflow({ cwd, write: true }).changed).toBe(false)
    expect(readFileSync(join(cwd, 'package.json'), 'utf8')).toContain('"expo": "~57.0.8"')
  })

  it('protects manual eas.json and generates a stable baseline explicitly', () => {
    const cwd = cleanRoom()
    writeFileSync(join(cwd, 'eas.json'), JSON.stringify({ build: { custom: {} } }))
    expect(runEasWorkflow({ cwd, write: true }).ok).toBe(false)
    expect(JSON.parse(readFileSync(join(cwd, 'eas.json'), 'utf8'))).toHaveProperty('build.custom')

    expect(runEasWorkflow({ cwd, write: true, force: true }).changed).toBe(true)
    expect(runEasWorkflow({ cwd, write: true, force: true }).changed).toBe(false)
  })

  it('verifies a clean-room project and identifies marked generated boundaries', () => {
    const cwd = cleanRoom()
    runUpgradeWorkflow({ cwd, write: true })
    runEasWorkflow({ cwd, write: true })
    mkdirSync(join(cwd, 'lib/api'), { recursive: true })
    writeFileSync(
      join(cwd, 'lib/api/index.ts'),
      '// Generated by npx pocketshot sync. Do not edit manually.\n',
    )
    const result = runVerifyWorkflow({
      cwd,
      release: true,
      env: {
        NODE_ENV: 'test',
        EXPO_PUBLIC_API_URL: 'https://api.example.com',
        EXPO_TOKEN: 'test-token',
      },
    })
    expect(result.ok).toBe(true)
    expect(result.generatedFiles).toEqual(['lib/api/index.ts'])
  })
})
