import { defineConfig } from 'tsup'

const peerDeps = [
  '@tanstack/react-query',
  'expo-router',
  'expo-secure-store',
  'jotai',
  'react',
  'react-native',
  'zod',
  // Optional native peers — duck-typed at runtime
  'react-native-maps',
  'react-native-markdown-display',
  'react-native-svg',
  'expo-camera',
  'expo-barcode-scanner',
  'expo-location',
  'expo-image-picker',
  'expo-document-picker',
  'expo-av',
  'expo-audio',
  'expo-haptics',
  '@gorhom/bottom-sheet',
  'react-native-safe-area-context',
  'react-native-gesture-handler',
  'react-native-passkeys',
  'expo-local-authentication',
  'expo-notifications',
  'expo-image',
  'expo-font',
  'expo-splash-screen',
  'expo-sqlite',
]

export default defineConfig([
  {
    entry: { cli: 'src/cli/index.ts' },
    format: ['cjs'],
    target: 'node18',
    bundle: true,
    noExternal: [/.*/],
    banner: { js: '#!/usr/bin/env node' },
    outDir: 'dist',
  },
  {
    entry: {
      index: 'src/index.ts',
      ui: 'src/ui.ts',
      realtime: 'src/realtime/index.ts',
      offline: 'src/offline/index.ts',
      drafts: 'src/drafts/index.ts',
      testing: 'src/testing/index.ts',
      media: 'src/media/index.ts',
      upload: 'src/upload/index.ts',
      push: 'src/push/index.ts',
      ai: 'src/ai/index.ts',
      auth: 'src/auth/index.ts',
      audio: 'src/audio/index.ts',
      billing: 'src/billing/index.ts',
      coach: 'src/coach/index.ts',
      party: 'src/party/index.ts',
      'party-session': 'src/party-session/index.ts',
      release: 'src/release/index.ts',
      privacy: 'src/privacy/index.ts',
      observability: 'src/observability/index.ts',
      accessibility: 'src/accessibility/index.ts',
      'app-state': 'src/app-state/index.ts',
      biometrics: 'src/biometrics/index.ts',
      'deep-links': 'src/deep-links/index.ts',
      device: 'src/device/index.ts',
      haptics: 'src/haptics/index.ts',
      organizations: 'src/organizations/index.ts',
      permissions: 'src/permissions/index.ts',
      search: 'src/search/index.ts',
      share: 'src/share/index.ts',
      sse: 'src/sse/index.ts',
      theme: 'src/theme/index.ts',
      webhooks: 'src/webhooks/index.ts',
      ws: 'src/ws/index.ts',
      community: 'src/community/index.ts',
      'community-core': 'src/community/core.ts',
    },
    format: ['esm', 'cjs'],
    sourcemap: true,
    external: peerDeps,
    outDir: 'dist',
  },
])
