import fs from 'node:fs/promises'
import path from 'node:path'
import { log, spinner } from '@clack/prompts'

interface ManifestScreenConfig {
  id: string
  title?: string
  components: unknown[]
}

interface ManifestResponse {
  name: string
  screens: Record<string, ManifestScreenConfig>
  theme?: unknown
}

export interface ManifestSyncOptions {
  apiUrl: string
  outDir: string
  cwd: string
}

/**
 * Fetches the manifest from the Slingshot server and generates:
 * - One screen file per route in `outDir/`
 * - A `manifest.ts` config file with the full ManifestConfig
 */
export async function runManifestSync(opts: ManifestSyncOptions): Promise<void> {
  const { apiUrl, outDir, cwd } = opts
  const absOut = path.resolve(cwd, outDir)

  const s = spinner()
  s.start(`Fetching manifest from ${apiUrl}`)

  let manifest: ManifestResponse
  try {
    const res = await fetch(`${apiUrl.replace(/\/$/, '')}/manifest`)
    if (!res.ok) throw new Error(`HTTP ${res.status}: ${res.statusText}`)
    manifest = (await res.json()) as ManifestResponse
  } catch (err) {
    s.stop('Failed to fetch manifest')
    throw new Error(`Could not fetch manifest: ${err instanceof Error ? err.message : String(err)}`)
  }

  s.stop(
    `Fetched manifest for "${manifest.name}" (${Object.keys(manifest.screens).length} screens)`,
  )

  await fs.mkdir(absOut, { recursive: true })

  // Write the manifest config file
  const manifestTs = generateManifestConfig(manifest)
  await fs.writeFile(path.join(absOut, 'manifest.ts'), manifestTs, 'utf8')
  log.success('Generated manifest.ts')

  // Write per-screen files
  for (const [routePath, screen] of Object.entries(manifest.screens)) {
    const fileName = routeToFileName(routePath)
    const screenTs = generateScreenFile(routePath, screen)
    await fs.writeFile(path.join(absOut, fileName), screenTs, 'utf8')
    log.success(`Generated ${fileName} (${routePath})`)
  }
}

function routeToFileName(route: string): string {
  // /posts/:id → posts.[id].ts
  return (
    route
      .replace(/^\//, '')
      .replace(/:(\w+)/g, '[$1]')
      .replace(/\//g, '.') + '.ts'
  )
}

function generateManifestConfig(manifest: ManifestResponse): string {
  return `// --- section:manifest ---
// Generated by pocketshot manifest. Safe to re-run — section markers preserve custom code.
import type { ManifestConfig } from '@lastshotlabs/pocketshot/ui'

export const manifest: ManifestConfig = ${JSON.stringify(manifest, null, 2)} as ManifestConfig
// --- end:manifest ---
`
}

function generateScreenFile(routePath: string, screen: ManifestScreenConfig): string {
  const componentName = routeToComponentName(routePath)
  return `// --- section:screen ---
// Generated by pocketshot manifest. Regenerated on \`pocketshot manifest\`.
import type { ScreenConfig } from '@lastshotlabs/pocketshot/ui'

export const ${componentName}Screen: ScreenConfig = ${JSON.stringify(screen, null, 2)} as ScreenConfig
// --- end:screen ---
`
}

function routeToComponentName(route: string): string {
  return route
    .replace(/^\//, '')
    .replace(/:(\w+)/g, (_, p: string) => p.charAt(0).toUpperCase() + p.slice(1))
    .split('/')
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('')
}
